dist: xenial
language: rust
rust:
  - nightly
  - beta
  - stable
env:
  - GTK=3.4
  - GTK=3.18
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
script:
  - rustc --version
  - cargo build
